### ISSUE TITLE
[Question] [Exposed vuex store] Is this a potential security issue?

### ISSUE THREAD

**Issue by areebbeigh** [gothinkster/vue-realworld-example-app#110]
**I'm still learning about Vue and am curious about this**

I can access and modify the store from the dev console as so:

`document.getElementsByTagName('a')[0].__vue__.$store.state`

Does this open potential security risks? Say for example, if there were a `isAdmin` attribute to validate user admin status stored in the state? Or if I could manipulate the user data that'd lead to a bad request to the server? 

If so, what would be the best way to avoid this?

**Comment by igeligel** [comment]
Client-side validation is never safe. Always secure your backend APIs.

So, there are 2 solutions to this problem:

1) You still have your frontend bundled into one file in the end. This opens the possibility for "hackers" to enable the `isAdmin` flag. But when they try to use the admin features the server should response with a `401 Not Authorized` error. This means even if the "hacker" found a way to enable the admin interface he is not able to use it.

2) The "hacker" is never able to load the JavaScript by the server responsible for the admin functionality. This can involve different techniques like serving JavaScript based on the authorization headers. What could be done for example is given a simple `index.html` it will load our Vue.js application under `/static/js/app.js`. This route though serves two different JavaScript applications based on authorization. One for the admin and one for the normal user. This involves backend logic anyway. You can even optimize this by creating one main bundle for both applications with shared code but 2 different bundles, one for the admin and one for the normal user to be loaded.

My recommendation is to use approach 1 and if your application/company gets really big think about 2). But in most cases 2) just does not make sense.

**Comment by areebbeigh** [comment]
That makes sense. Thanks.
