### ISSUE TITLE
Service-worker file missing

### ISSUE THREAD

**Issue by mr-lanholmes** [gothinkster/vue-realworld-example-app#112]
Hi all,

Am I missing the service-worker.js file? or will it be auto-generated during the build process? Thanks!

**Comment by igeligel** [comment]
It will be auto-generated. You can see the code doing this here somehow: https://github.com/gothinkster/vue-realworld-example-app/blob/eeaeb34fa440d00cd400545301ea203bd2a59284/src/registerServiceWorker.js

**Comment by igeligel** [comment]
@mr-lanholmes Can I close this issue?
