### ISSUE TITLE
Follow user not working on article page

### ISSUE THREAD

**Issue by disjfa** [gothinkster/vue-realworld-example-app#12]
On the article page the follow user button is not working.

**Comment by techiedod** [comment]
I can look at this issue tomorrow in the morning if no one fixes it before then.

**Comment by disjfa** [comment]
Cool, i do have an open pullrequest wich will create a conflict

**Comment by techiedod** [comment]
@disjfa When do you plan to merge it?

**Comment by disjfa** [comment]
I want people to see the changes and comment, so when that happens. At least a couple of days.
