### ISSUE TITLE
The script has an unsupported MIME type ('text/html').

### ISSUE THREAD

**Issue by luckylooke** [gothinkster/vue-realworld-example-app#129]
Hello!

First of all thank you for your amazing work! :)

I have clean install of your repo and wwithout any changes I am getting console error `The script has an unsupported MIME type ('text/html').` without any further info.. I currently have no idea how to find the file causing this.

Thank you for any idea. 
Happy coding ;)

**Comment by 12vanblart** [comment]
Are you still getting this error? 

If so, what browser are you using?

**Comment by luckylooke** [comment]
no, cannot reproduce now 👍 thanks
