### ISSUE TITLE
Using vue-function-api

### ISSUE THREAD

**Issue by afattahi54** [gothinkster/vue-realworld-example-app#161]
Is there any plan to update this sample and use vue-function-api plugin.
It seems that the vue-function-api will be used in Vue 3.0 too

**Comment by igeligel** [comment]
Hey @afattahi54, the proposal is still an active RFC which means it is not sure if this will be implemented.

You can see the RFC here: https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md

Especially issues like this https://github.com/vuejs/vue-function-api/issues/8#issuecomment-506239327 are showing that the migration to the plugin is kind of risky. I would leave it up when the beta of Vue 3 is released.

I will leave a mark in the FAQ of the [README.md](https://raw.githubusercontent.com/gothinkster/vue-realworld-example-app/master/README.md)
