### ISSUE TITLE
What is the meaning of using [async/await ]

### ISSUE THREAD

**Issue by Allianzcortex** [gothinkster/vue-realworld-example-app#190]
Hey , just curious about why we need to use async/await in our actions:
e.g.

"""
async [FAVORITE_REMOVE](context, payload) {
    const { data } = await FavoriteService.remove(payload);
    context.commit(UPDATE_ARTICLE_IN_LIST, data.article, { root: true });
    context.commit(SET_ARTICLE, data.article);
  },
"""

for the  2nd line : `context.commit(UPDATE_ARTICLE_IN_LIST)` , it still needs to use the returned
result from 1st line to finish the function. So the `await FavoriteService.remove(payload)` makes no sense because we must wait to reach to the next line until it is finished.

I'm not sure whether I have a right understanding, looking forward to furthering discussions.~

**Comment by morficus** [comment]
When you use `await`, the lines below that will not get executed until the `await`'ed function returns a value.

If you are comfortable with Promises but more familiar with the callback syntax, your above code is equivalent to writing this:
```js
[FAVORITE_REMOVE](context, payload) {
     FavoriteService
     .remove(payload)
     .then({ data} => {
          context.commit(UPDATE_ARTICLE_IN_LIST, data.article, { root: true });
          context.commit(SET_ARTICLE, data.article);
      })
},
```

**Comment by Allianzcortex** [comment]
@morficus yeah... I get what you mean now. we use await to make sure we can get the data returned by axios post
