### ISSUE TITLE
CommentEditor: Use shorthand for directive

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#198]
In the [`CommentEditor.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/06f5939c4ccfd07045a73bbbe26b8cfd2d684556/src/components/CommentEditor.vue) component we are using something like `v-on:submit.prevent="onSubmit(slug, comment);"`. We should rather use the shorthand version with `@`.

**Resources**

- https://vuejs.org/v2/style-guide/#Directive-shorthands-strongly-recommended

**Comment by ikrydev** [comment]
Please assign me to this...

**Comment by ikrydev** [comment]
#217

**Comment by ikrydev** [comment]
close this , because its was merged @igeligel
