### ISSUE TITLE
CommentEditor: Use PascalCase for imported components

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#199]
In the [`CommentEditor.vue` component](https://github.com/gothinkster/vue-realworld-example-app/blob/06f5939c4ccfd07045a73bbbe26b8cfd2d684556/src/components/CommentEditor.vue), the `RwvListErrors` is imported, and used as `rwv-list-errors`. It should rather be used as `RwvListErrors`.

**Resources**

- https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended

**Comment by Shanmugapriya03** [comment]
Have Raised a PR for this issue #219  @igeligel
