### ISSUE TITLE
No favicons in the index.html page

### ISSUE THREAD

**Issue by morficus** [gothinkster/vue-realworld-example-app#2]

**Comment by igeligel** [comment]
We should rather use a webpack plugin to support stuff like this in my opinion. I am fine with merging #3 but we should leave open this issue and extend it then.

Webpack plugin for [favicons](https://github.com/jantimon/favicons-webpack-plugin).

[Vue plugin](https://github.com/declandewet/vue-meta) for changing the meta tags.

**Comment by morficus** [comment]
Interesting. Was not aware that there was a webpack plugin to generate this (tho I'm not surprised haha). I can configure it and open another PR with that if that is preferred.

**Comment by igeligel** [comment]
It is preferred i think. But let's wait for another opinion. I do not want to decide on this alone 🤔 

The meta tag change would require a lot of changes since it needs to be adjusted for every view i guess since the title should be different.

**Comment by morficus** [comment]
ok... I created a 2nd alternative PR that uses the webpack plugin. That way regardless of what direction people decide to go in... the work is already done :-)

I also removed the `color-theme` meta tag from the original PR, since that would probably fall under the hole "title tag management" stuff

**Comment by vilsbole** [comment]
@igeligel The webpack plugin seems like a great option to generate the appropriate favicons. I'm merging the PR #4 and closing the PR #3
