### ISSUE TITLE
CommentEditor: Use relative imports

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#200]
In the [`CommentEditor.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/06f5939c4ccfd07045a73bbbe26b8cfd2d684556/src/components/CommentEditor.vue) component webpack's alias imports are used:

```js
import ... from "@/...";
// ...
```

Instead, we should use relative imports. It is easier to refactor later.

**Resources**

- https://til.hashrocket.com/posts/38d2d28b6b-better-module-imports-with-webpack-aliases (it says, it is good but makes refactoring a lot harder...)

**Comment by chinmay81098** [comment]
Created PR for this issue #220
