### ISSUE TITLE
Tests: Hide gitignore coverage reports

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#201]
**Current State**

When running `yarn test` the test command will create coverage reports. Those coverage reports will appear as files in `git`.

**Expected State**

- coverage reports do not show up in `git`

**Comment by Shanmugapriya03** [comment]
Have Raised a PR for this issue #218  @igeligel

**Comment by Shanmugapriya03** [comment]
#218 PR has been merged
Can you close this issue @igeligel it is still open
