### ISSUE TITLE
Login and Register both fail the first time

### ISSUE THREAD

**Issue by AlexanderOpran** [gothinkster/vue-realworld-example-app#21]
Including both the live demo and my local cloned project, every single time you try to login and register with valid credentials, it silently fails (without any errors). The second or third time,  etc.,  it works.

I suppose the problem lies somewhere in the vuex implementation.

**Comment by AlexanderOpran** [comment]
For some reason, the first time I try to register, the `POST `to the `/users `endpoint is made before the `mongoose user.insert`.

`POST /users - - ms - -`

**Comment by AlexanderOpran** [comment]
It seems that the first Login Or Register request doesn't even reach the server.

**Comment by AlexanderOpran** [comment]
Listening on port 3000
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
Mongoose: articles.ensureIndex({ slug: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })
Mongoose: users.findOne({ email: 'firstLoginAttempt@mail.com' }, { fields: {} })
POST /users/login - - ms - -

Mongoose: users.findOne({ email: 'secondLoginAttempt@mail.com' }, { fields: {} })
POST /users/login 200 98.776 ms - 314
Mongoose: users.findOne({ _id: ObjectId("5a9b776ae3b19508b0bb29e8") }, { fields: {} })
GET /user/ 200 10.098 ms - 314
Mongoose: users.findOne({ _id: ObjectId("5a9b776ae3b19508b0bb29e8") }, { fields: {} })
GET /user/ 304 9.706 ms - -

**Comment by AlexanderOpran** [comment]
I solved these issues by changing `v-on:submit="onSubmit"` to  `v-on:submit.prevent="onSubmit"` in the Register and Login forms.

**Comment by vilsbole** [comment]
Thanks for pointing this out!
If I understand correctly you're running the api locally and changed the frontend project to use your local api, and 'onSubmit' doesn't trigger a call to the api ?
