### ISSUE TITLE
Use shorthand for directive in all the components

### ISSUE THREAD

**Issue by worldofprasanna** [gothinkster/vue-realworld-example-app#244]
I noticed that few components don t have shorthand notation and it was addressed in few of the other issues as well. We can fix all the components at one stretch.

https://github.com/gothinkster/vue-realworld-example-app/issues/198

It is recommended to use @ instead of v-on for the directives.

**Recommendation**: https://vuejs.org/v2/style-guide/#Directive-shorthands-strongly-recommended

**Components which has v-on:**
1. ArticleMeta
2. Comment
3. ArticleEdit
4. Login
5. Register

**Comment by henryraygan** [comment]
i fixed this, is ok?

**Comment by worldofprasanna** [comment]
@henryraygan the PR which I have submitted is already merged. I saw your commit, it contains few other changes also. Might be you can open a new issue stating all those changes and could raise a new PR for it.

I will close this issue now.
