### ISSUE TITLE
Tags cloud doesnt work

### ISSUE THREAD

**Issue by outluch** [gothinkster/vue-realworld-example-app#274]
I click on tag but nothing happens. https://vue-vuex-realworld.netlify.com/#/
In original version it works: https://demo.realworld.io/#/

**Comment by igeligel** [comment]
Hey @outluch ,

I cannot reproduce this:

![](https://i.imgur.com/8yayajM.gif)

It is working as expected. Closing this issue in 24 hours if there are no other concerns.

**Comment by mindochin** [comment]
confirm, not work
![record_000001](https://user-images.githubusercontent.com/1146472/70211565-41b20200-1757-11ea-8521-32acd98bfcfd.gif)
