### ISSUE TITLE
Why do we need checked auth before each page load?

### ISSUE THREAD

**Issue by tranlehaiquan** [gothinkster/vue-realworld-example-app#35]
I find in ```main.js```, 
```javascript
// Ensure we checked auth before each page load.
router.beforeEach(
  (to, from, next) => {
    return Promise
      .all([store.dispatch(CHECK_AUTH)])
      .then(next)
  }
)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: { App }
})
```
Instead of that why don't we just create an Action to check just only one time when enter site?
```javascript
store.dispatch('CHECK_AUTH')
  .then(() => {
    /* eslint-disable no-new */
    new Vue({
      el: '#app',
      store,
      router,
      components: { App },
      template: '<App/>'
    })
  })
```
It reduce request from each time change from another page? (may be faster?)

**Comment by tranlehaiquan** [comment]
@igeligel so we received token and add it to cookie instead localstorage?

**Comment by igeligel** [comment]
Hmm the official guide recommends to use localstorage:

```
Sign in/Sign up pages (URL: /#/login, /#/register )
Use JWT (store the token in localStorage)
```

[Source](https://github.com/gothinkster/react-redux-realworld-example-app/blob/cde2bda6e6d16a61df85323f4930b5335b126a6c/README.md)

I know for sure localstorage is not right. Maybe we can create an issue in the master repository about it.

**Comment by vilsbole** [comment]
@tranlehaiquan: 
I have a few hesitations on a single auth check. 
What happens when a user is authenticated -> then logout -> and leaves the browser tab open?
Wouldn't the app will continue to behave as if it were authenticated and the routes that require auth will still be accessible?

The route guard is intended to protect certain routes such as /settings or /editor, and a single auth check wouldn't be sufficient. 

In any case thanks for your suggestion. It's an a good reminder that the guard still needs to be implemented! I opened issue #39 for this.

**Comment by tranlehaiquan** [comment]
@vilsbole 
You mean leave another browser tab open, and it still has token, right?

**Comment by tranlehaiquan** [comment]
Got it, I try to fix it soon.

**Comment by cliffordh** [comment]
Should not the JWT token always pass to the backend (excluding of course login/register), and the backend either returns the response or a 401 not authorized or 403 forbidden (in the case of accessing resources that do not belong to the authenticated user)? It seems every API call should set the auth header and leave it to the backend to return the appropriate HTTP response code. We should not have an auth check API call before every 'real' call to the API...

**Comment by tranlehaiquan** [comment]
Close this issue : ), because not working on it anymore.
