### ISSUE TITLE
Upgrade Vue 3?

### ISSUE THREAD

**Issue by bakbuz** [gothinkster/vue-realworld-example-app#450]
Could you upgrade to Vue.js version 3? Is it possible?

**Comment by levchak0910** [comment]
@bakbuz, [here](https://github.com/mutoe/vue3-realworld-example-app) is version using vue3, but not official

**Comment by bakbuz** [comment]
> @bakbuz, [here](https://github.com/mutoe/vue3-realworld-example-app) is version using vue3, but repo is not official

It's looking pretty good. Thank you very much.
