### ISSUE TITLE
Hosting of example application

### ISSUE THREAD

**Issue by vilsbole** [gothinkster/vue-realworld-example-app#563]
I will stop hosting the example application on te 18/07.
Is there a current maintainer who wishes, I can transfer the ownership of the current Netlify app?

**Comment by jasurkurbanov** [comment]
I want to be a maintainer of this project. Can you add me as a maintainer ?

**Comment by swrzalek** [comment]
@vilsbole also interested of taking care of it.

**Comment by vilsbole** [comment]
Hi, thanks for you interest! 
I've added you both as contributors, so you will be able to submit, review, and merge MR's. 
Have fun!
