### ISSUE TITLE
Do not access the store object directly from components

### ISSUE THREAD

**Issue by morficus** [gothinkster/vue-realworld-example-app#6]
## The Problem
For large and real-world applications... writing `this.$store. getters` and  `this.$store. dispatch ` gets quite tedious and creates temptation for trying to modify things directly (such as `this.$store.state.myThing = 'the new thing'`)

## Recommended Solution
Leverage the 3 helper methods offered by Vuex ([mapState](https://vuex.vuejs.org/en/state.html#the-mapstate-helper), [mapGetters](https://vuex.vuejs.org/en/getters.html#the-mapgetters-helper) and [mapActions](https://vuex.vuejs.org/en/actions.html#dispatching-actions-in-components)).

**Comment by techiedod** [comment]
Hey guys,

What's the state of this issue. I'm available to contribute with whatever is necessary to get this example ready for publication.

**Comment by disjfa** [comment]
As far as i know this has been fixed 99% in https://github.com/gothinkster/vue-realworld-example-app/pull/8
