### ISSUE TITLE
Fix path of imported modules in ArticleList.vue

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#64]
**Issue summary**

In [`src/components/ArticleList.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ArticleList.vue#L25-L27) some local modules are imported with the `@` symbol which is a webpack alias. For people which are not familar with webpack this might be confusing. Change this to a relative pattern.

**Resources**

- webpack - [Resolve](https://webpack.js.org/configuration/resolve/)

**Acceptance Criteria**

- Every `@` in the import statements is replaced with a relative path.

**Comment by moozzyk** [comment]
Sent a PR to address this.
