### ISSUE TITLE
Normalize config module

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#69]
**Issue Summary**

In the module [`src/common/config.js`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/common/config.js) there is a default module defined which is an empty object. Instead export the `API_URL` also as default export.

**Resources**

- MDN - [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
- MDN - [export](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export)
- stackoverflow - [Import Statements in ES6 from MDN docs](https://stackoverflow.com/questions/51215691/import-statements-in-es6-from-mdn-docs)

**Acceptance Criteria**

- Module is exporting `API_URL` as named and default export

**Comment by jkmdev** [comment]
I'll give this one a shot
