### ISSUE TITLE
Normalize JwtService exports

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#70]
**Issue Summary**

In the module [`jwt.service.js`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/common/jwt.service.js) there is just a default module. All of the functions of the default `export` should exist as own functions and should be exported as named `exports`.

**Resources**

- MDN - [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
- MDN - [export](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export)
- stackoverflow - [Import Statements in ES6 from MDN docs](https://stackoverflow.com/questions/51215691/import-statements-in-es6-from-mdn-docs)

**Acceptance Criteria**

- The functions `getToken`, `saveToken` and `destroyToken` can be imported like `import { getToken, saveToken, destroyToken } from ".../jwt.service" ` but also the full object can be imported like `import JwtService from ".../jwt.service"`.

**Comment by matheushf** [comment]
#78
