### ISSUE TITLE
Refactor free text in ArticleActions

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#71]
**Issue summary**

In [`src/components/ArticleActions.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ArticleActions.vue) there are a lot of free texts which should be wrapped with `<span>`s or similar. Look for example:

```vue
<router-link
  class="btn btn-sm btn-outline-secondary"
  :to="{ name: 'article-edit', params: { slug: this.article.slug } }">
  <i class="ion-edit" />&nbsp;Edit Article
</router-link>
```

Should be

```vue
<router-link
  class="btn btn-sm btn-outline-secondary"
  :to="{ name: 'article-edit', params: { slug: this.article.slug } }">
  <i class="ion-edit" /><span>&nbsp;Edit Article</span>
</router-link>
```

Replace every free character/word which is not wrapped with a `<span></span>`.

**Acceptance Criteria**

- All texts in the `ArticleActions.vue` component are wrapped with `<span></span>` elements

**Comment by oktak** [comment]
Let me take this. Are those free character/word located mainly in the ```<template>``` part?
