### ISSUE TITLE
Refactor method calls in ArticleActions

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#75]
**Issue summary**

In the component [`src/components/ArticleActions.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ArticleActions.vue) a lot of on click handlers are triggered and are calling a method with an instance property. For example there is a handler calling `deleteArticle(article.slug)` even though `article.slug` is bound to this. Rather just use `deleteArticle` and refactor the instance function to something like:

```js
deleteArticle() {
  this.$store.dispatch(ARTICLE_DELETE, this.article.slug).then(() => {
    this.$router.push("/");
  });
}
```

**Acceptance criteria**

- The `deleteArticle` function in the `ArticleActions.vue` component does not take a parameter
- The `toggleFollow` function in the `ArticleActions.vue` component does not take a parameter
- The `toggleFavorite` function in the `ArticleActions.vue` component does not take a parameter

**Comment by GianOrtiz** [comment]
Will work on it.
