### ISSUE TITLE
Use async/await in method and extend error handling

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#79]
**Issue summary**

The [`deleteArticle`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ArticleActions.vue#L90-L94) is using a Promise even though it could use the async/await pattern.

**Resources**

- MDN - [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)
- javascript.info - [async tutorial](https://javascript.info/async)
- MDN - [try...catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)

**Acceptance criteria**

- There are no `.then(...` call in the function anymore
- `async` and `await` are used
- A try-catch block was introduced to handle errors and the page is not redirecting to the homepage

**Comment by franciscoemanuel** [comment]
I can do this one!
