### ISSUE TITLE
Normalize template of TheFooter

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#82]
**Issue summary**

In the [`src/components/TheFooter.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/TheFooter.vue) there is no new line between `<template></template>` and `<script></script>`. But there should be a new line.

**Acceptance criteria**

- The `<template></template>` and `<script></script>` part are separated by a new line in `src/components/TheFooter.vue` component

**Comment by islamnurdin** [comment]
See my pull request and let me know if there is something else.
