### ISSUE TITLE
Rename component name in TheFooter

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#83]
**Issue summary**

The name in [`src/components/TheFooter.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/TheFooter.vue) is not PascalCase.

**Acceptance criteria**

- `rwvFooter` should be `RwvFooter` in the [`src/components/TheFooter.vue`](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/TheFooter.vue) component

**Comment by rhellyar** [comment]
I'll happily take this up
