### ISSUE TITLE
Exclude moment from the dependencies

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#9]
I think it is not worth to include a library here for a simple date filter. The functionalities of moment are used once and it is really simple to exclude this here.

`vue-realworld-example-app/src/common/date.filter.js`:

```js
import moment from 'moment'

export default (date) => {
  return moment(date).format('MMM DD, YYYY')
}
```

Can be easily transferred to a native solution.

**Comment by vilsbole** [comment]
Indeed, it is overkill to import the full library for simple date formatting (I was expecting to use it more). But, I also seek to avoid reinventing the wheel.
Since it seems that `moment` will not become modular in the near future (https://github.com/moment/moment/issues/2373), what do you think of using the suggested `date-fns` ? 

```
import { format } from 'date-fns/esm'
```

**Comment by morficus** [comment]
Is this concern of "including a full lib for 1 function" go away with tree-shaking in WebPack?

**Comment by maggiepint** [comment]
Just to note, we (the moment team) shipped a new library which is a moment-like API built for the modern web. It will only work with evergreen browsers, but it does pretty much everything moment does - including full time zone support. It's smaller, it's shakeable, and it's here: https://github.com/moment/luxon

You're more than welcome to go down the date-fns road as well of course - it's a great library. Luxon's API is much closer to Moment's though.

**Comment by atilacamurca** [comment]
the [react-redux](https://github.com/gothinkster/react-redux-realworld-example-app) example uses:

```
new Date(article.createdAt).toDateString()
```

as you can see in <https://github.com/gothinkster/react-redux-realworld-example-app/blob/3e550111a601d36fd6509bf670b85f212dbf35dd/src/components/Article/ArticleMeta.js#L18>

The point to consider is also l10n.
