### ISSUE TITLE
Wrap key in span in the ListErrors component

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#93]
**Issue summary**

In [ListErrors.vue](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ListErrors.vue) there is an element being rendered. This element is `{{key}}` but is not wrapped by a `<span>` but should be.

**Acceptance criteria**

- In [ListErrors.vue](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ListErrors.vue) the key template is wrapped in a `<span>`

**Comment by igeligel** [comment]
@luvuong-le Would be really great. If you need help just ping me here.

**Comment by luvuong-le** [comment]
@igeligel Seems like there's already been a pull request, I'll leave it to them to resolve this issue
