### ISSUE TITLE
Create test cases for ListErrors

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#95]
**Issue summary**

A unit test should be created for the [ListErrors.vue](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ListErrors.vue) component. It should be in the [`/tests/unit/components`](https://github.com/gothinkster/vue-realworld-example-app/tree/master/tests/unit/components) component. There are also similar examples in this folder for unit tests. The component should be tested for different `errors` props.

**Acceptance criteria**

- A unit test is created and passing for the [ListErrors.vue](https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ListErrors.vue) component

**Comment by luvuong-le** [comment]
I'll give this a go
